### ISSUE TITLE
Train failed

### ISSUE THREAD

**Issue by StarsTesla** [NVlabs/nvdiffrecmc#23]
Hi there, I tried to run this code and I get an error of :

[F glutil.cpp:332] eglGetDisplay() failed
Aborted (core dumped)

My env is:
Ubuntu 20.04 server
GPU A100 40G
python 3.9
CUDA 11.7
Pytorch 2.0.0

**Comment by jmunkberg** [comment]
Hello, 

What config did you run? Please check our Dockerfile for the opengl setup on Linux (same as nvdiffrast)
https://github.com/NVlabs/nvdiffrecmc#server-usage-through-docker

https://github.com/NVlabs/nvdiffrecmc/blob/main/docker/Dockerfile

**Comment by StarsTesla** [comment]
Sorry to bother you it seems that our GPU got some problem(nvidia-smi shows Disabled on the right), and we changed to another 3090, which can be rightly ran, thanks for your great work.
