### ISSUE TITLE
some confusion about source

### ISSUE THREAD

**Issue by blacksino** [NVlabs/nvdiffrecmc#30]
Hello, I noticed that in the source code, you first used nvdiffrast to compute the global positions. May I ask if the use of rasterization rendering is for the initialization of ray tracing? I'm not quite sure why nvdiffrast is used in a rendering process that's based on ray tracing.

**Comment by jmunkberg** [comment]
Hello @blacksino ,

We leverage nvdiffrast to compute (differentiable) primary visibility through rasterization and only apply ray tracing for the shadow rays traced in the hemisphere at each shading point.

It is certainly possible to also use differentiable ray tracing, e.g., http://people.csail.mit.edu/sbangaru/projects/was-2020/ for the primary visibility, but it is often a bit more computationally expensive, and nvdiffrast worked well for our purposes.

**Comment by blacksino** [comment]
Thank you for your kind explaination
