### ISSUE TITLE
geometry issue

### ISSUE THREAD

**Issue by blacksino** [NVlabs/nvdiffrecmc#31]
sorry for bothering again. great works always takes a lot to fully understand.
When the SDF (Signed Distance Field) is randomly initialized, the geometry can be considered to be in a 'broken' state, with non-adjacent triangular patches scattered throughout the space. We also noticed that the operation of Marching Tets determining which tetrahedra contain a surface does not participate in gradient computation, which means that only some of the vertices could participate in the geometry update. Moreover, during each iteration, it is uncertain which vertices will be updated, and to some extent, it is not guaranteed that the generated geometry is continuous. In this situation, it is hard for me to intuitively understand the optimization of the geometry part, and it is unclear whether the geometry part will have difficulty converging.
Did I misunderstand, or did I overlook some details?

**Comment by jmunkberg** [comment]
Thanks @blacksino ,

Please refer to the DMTet paper, Section 3.1.3 for a discussion of the convergence properties of Differentiable Marching Tetrahedra: https://nv-tlabs.github.io/DMTet/
