### ISSUE TITLE
Light estimation: Nvdiffrecmc vs nvdiffrec

### ISSUE THREAD

**Issue by Selozhd** [NVlabs/nvdiffrecmc#4]
I am concerned about the differences in light estimation for nvdiffrecmc compared to nvdiffrec. It appears at first sight that the light estimation takes some qualities of the material. 

I am following the same procedure and config, which I described in a [similar issue I opened in nvdiffrec for light estimation](https://github.com/NVlabs/nvdiffrec/issues/80). (except reduced dmtet_grid to 128 from 256 due to gpu memory issues, and the new defualt 3000.0 for the laplace_scale) Shortly, I am generating a synthetic dataset in blender under a given environment map and give the model the same dataset for joint light, material, and mesh optimization.

Here are the environment map I gave, and light estimations by nvdiffrecmc and nvdiffrec respectively:
- [original light](https://user-images.githubusercontent.com/41761641/195031828-ae19bf3c-84a6-42da-b0b0-6fd5f5f988e6.png)
- [probe.hdr estimated by nvdiffrecmc](https://user-images.githubusercontent.com/41761641/195031403-440f1f76-42ae-49dd-a08c-f8a20f575b9d.png)
- [probe.hdr estimated by nvdiffrec](https://user-images.githubusercontent.com/41761641/195031672-70ce4f97-75a9-4684-9e49-266448db0194.png)

As you can see the light estimation has a blue hue. Furthermore, I think the light estimation also affects the quality of the final mesh. I am sharing a photograph below from the final mesh and an nvdiffrecmc rendering from the training. As you can see, the front of the shoe is missing in the mesh while the nvdiffrecmc render looks ok. I never experienced this kind of mesh deformation in nvdiffrec.

<img width="407" alt="Screenshot 2022-10-10 at 18 24 12" src="https://user-images.githubusercontent.com/41761641/195038046-326fe8df-9b21-4b86-8281-a10ac6ac21d8.png">

![](https://user-images.githubusercontent.com/41761641/195038173-d1ec3366-d4da-4155-bb66-da6de31bfdb7.png)

**Comment by JHnvidia** [comment]
Hello,

In the original nvdiffrec we used a simple white-balance regularizer for the light (code is available here: https://github.com/NVlabs/nvdiffrec/blob/main/render/light.py#L81). We removed it at some point while writing the new paper, but didn't have really strong arguments either way. It should be relatively easy for you to add back in.

There's no real right or wrong here, since it's impossible to disambiguate a blue materal from a scene with blue lighting. For photo-capture it's probably a good idea to have some form of regularizer that mimics natural sunlight.

**Comment by Selozhd** [comment]
Oh thanks, I didn't realize this! Will try and get back to you with the results.

**Comment by Selozhd** [comment]
I have rerun the trial with the same config, adding the white-balance regularization. Here is the new probe.hdr and a photograph of the final mesh. Just looking at these images, I think there is a considerable improvement. 

However, I still don't understand why **the sole has a hole**.

<img width="917" alt="Screenshot 2022-10-11 at 16 25 10" src="https://user-images.githubusercontent.com/41761641/195138529-b501cca3-e0ee-4b94-b1b1-08ffbe0e4a40.png">

![probe](https://user-images.githubusercontent.com/41761641/195138548-2f5972b1-9ef3-4708-b46b-40465d686059.png)

**Comment by JHnvidia** [comment]
We've changed geometry regularization a bit to favor more "smooth" surfaces, by applying a geometric normal regularizer. 
https://github.com/NVlabs/nvdiffrecmc/blob/main/render/regularizer.py#L48
This helped some scenes, particularly the ones with specular reflections, but degraded quality in scenes with complex geometry (e.g. NeRF-Lego).

More importantly, though, geometric optimization is considerably more complex when including the shadowing term. Adding or carving out geometry can considerably change the shading of a part of the scene, which causes discontinuities in the training. It could be the cause of the hole, but I've mostly noted the system failing or being to conservative in carving out geometry. We're adding the shadow term incrementally during training, so you could try to delay the scheduling, or defer lighting/shadowing entirely to the system's second pass.
https://github.com/NVlabs/nvdiffrecmc/blob/main/geometry/dmtet.py#L220

It should also be noted that we see the most benefit of the new system on scenes with strong directional lighting / complex shadowing (which is still hard). In your case, with a very smooth ambient light and limited shadowing (except for the inside of the shoe) it might be actually better to take some of the regularization ideas from the new paper and use the old system.

**Comment by Selozhd** [comment]
I implemented the shadowing delay used a more complex lighting. It appears that the shadowing delay is very helpful, delaying it to the second pass gave me the best results and removed the hole completely. This is also in good contrast to nvdiffrec where the sole was filled and in a dark colour.

@JHnvidia, thank you for your comments! 

![second_pass_shadow](https://user-images.githubusercontent.com/41761641/197144284-39143e09-334f-4bf5-954c-fd55ac1bde18.png)

![nvdiffrec](https://user-images.githubusercontent.com/41761641/197144711-d04fbca1-2f72-4c20-b812-6c9382c9274c.png)
