### ISSUE TITLE
break when run the code

### ISSUE THREAD

**Issue by semchan** [NVlabs/nvdiffrecmc#5]
Hi, thanks for your work. 

When I run the training code, it break here "self.optix_ctx = ou.OptiXContext()". it just pop out "Cuda path /usr/local/cuda" . could you please help me? thanks a lot.

**Comment by JHnvidia** [comment]
Hello

If that intialization code fails it likely means that our code cannot find OptiX. Nowdays, OptiX is distributed with the NVIDIA drivers and requires a recent version (see https://developer.nvidia.com/designworks/optix/download). We recommend using a recent card with RTX-support, preferably 30XX-series.

We primarily develop on Windows and rely pre-bundled OS/Docker images on our DGX servers, so unfortunately I cannot help if you have a custom installation issue. On Linux we have noted issues with graphics driver version (which controls OptiX version) and installed CUDA version. Using a more recent version of CUDA than Driver/OptiX usually does not work.

If you would like to debug the error a bit more, `ou.OptiXContext()` calls in to the following C-code. You could add some extra `printf("");` statements to see what fails.
https://github.com/NVlabs/nvdiffrecmc/blob/main/render/optixutils/c_src/optix_wrapper.cpp#L305

**Comment by semchan** [comment]
> Hello
> 
> If that intialization code fails it likely means that our code cannot find OptiX. Nowdays, OptiX is distributed with the NVIDIA drivers and requires a recent version (see https://developer.nvidia.com/designworks/optix/download). We recommend using a recent card with RTX-support, preferably 30XX-series.
> 
> We primarily develop on Windows and rely pre-bundled OS/Docker images on our DGX servers, so unfortunately I cannot help if you have a custom installation issue. On Linux we have noted issues with graphics driver version (which controls OptiX version) and installed CUDA version. Using a more recent version of CUDA than Driver/OptiX usually does not work.
> 
> If you would like to debug the error a bit more, `ou.OptiXContext()` calls in to the following C-code. You could add some extra `printf("");` statements to see what fails. https://github.com/NVlabs/nvdiffrecmc/blob/main/render/optixutils/c_src/optix_wrapper.cpp#L305

Noted with thanks.
